/** Typical metro on-road for one volume variant — not a quote, not every trim. */
export const CARS = [
  {
    id: "alto-k10",
    year: 2025,
    make: "Maruti Suzuki",
    model: "Alto K10",
    trim: "VXi",
    body: "hatch",
    condition: "new",
    auto: false,
    onRoad: 590000,
    seats: 5,
    kmpl: 24.4,
    fuel: "petrol",
    safety: 2,
    safetySource: "GNCAP-class",
    size: "small",
    parking: 10,
    reliability: 9,
    fun: 3,
    comfort: 4,
    trip: 4,
    cargo: 8,
    clearance: 5,
    rangeKm: null,
    kmPerKwh: null,
    summary: "The cheapest new car that still gets you through a city. Not a family crash structure.",
    caveat: "Two-star safety. Already no if kids ride along.",
  },
  {
    id: "wagonr-cng",
    year: 2025,
    make: "Maruti Suzuki",
    model: "WagonR",
    trim: "VXi CNG",
    body: "hatch",
    condition: "new",
    auto: true,
    onRoad: 840000,
    seats: 5,
    kmpl: 34.0,
    fuel: "cng",
    safety: 2,
    safetySource: "unrated-poor",
    size: "small",
    parking: 9,
    reliability: 9,
    fun: 3,
    comfort: 5,
    trip: 5,
    cargo: 10,
    clearance: 6,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Tall-boy plus factory CNG. A Delhi/Mumbai/Pune running-cost weapon.",
    caveat: "No CNG network in Bengaluru, Hyderabad, Chennai, or ‘another city’ in this model. Weak crash rating.",
  },
  {
    id: "tiago",
    year: 2025,
    make: "Tata",
    model: "Tiago",
    trim: "XZ",
    body: "hatch",
    condition: "new",
    auto: true,
    onRoad: 790000,
    seats: 5,
    kmpl: 19.0,
    fuel: "petrol",
    safety: 4,
    safetySource: "GNCAP",
    size: "small",
    parking: 9,
    reliability: 6,
    fun: 5,
    comfort: 5,
    trip: 5,
    cargo: 10,
    clearance: 5,
    rangeKm: null,
    kmPerKwh: null,
    summary: "The hatch that actually has a crash rating. Tight monthly money without giving up 4 stars.",
    caveat: "Service experience is the Tata tax. Rear seat is not a Creta.",
  },
  {
    id: "swift",
    year: 2025,
    make: "Maruti Suzuki",
    model: "Swift",
    trim: "ZXi",
    body: "hatch",
    condition: "new",
    auto: true,
    onRoad: 960000,
    seats: 5,
    kmpl: 22.4,
    fuel: "petrol",
    safety: 2,
    safetySource: "BNCAP",
    size: "small",
    parking: 9,
    reliability: 9,
    fun: 7,
    comfort: 5,
    trip: 5,
    cargo: 9,
    clearance: 5,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Still the hatch India enjoys driving. Bharat NCAP does not love it.",
    caveat: "2-star BNCAP. Popular is not the same as shortlistable with kids.",
  },
  {
    id: "baleno",
    year: 2025,
    make: "Maruti Suzuki",
    model: "Baleno",
    trim: "Zeta",
    body: "hatch",
    condition: "new",
    auto: true,
    onRoad: 1040000,
    seats: 5,
    kmpl: 22.3,
    fuel: "petrol",
    safety: 4,
    safetySource: "GNCAP",
    size: "small",
    parking: 8,
    reliability: 9,
    fun: 5,
    comfort: 6,
    trip: 6,
    cargo: 12,
    clearance: 5,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Premium hatch space with Maruti service. The grown-up Swift.",
    caveat: "Not an SUV. Bad roads will remind you.",
  },
  {
    id: "i20",
    year: 2025,
    make: "Hyundai",
    model: "i20",
    trim: "Sportz",
    body: "hatch",
    condition: "new",
    auto: true,
    onRoad: 1100000,
    seats: 5,
    kmpl: 20.2,
    fuel: "petrol",
    safety: 3,
    safetySource: "GNCAP",
    size: "small",
    parking: 8,
    reliability: 7,
    fun: 6,
    comfort: 6,
    trip: 6,
    cargo: 11,
    clearance: 5,
    rangeKm: null,
    kmPerKwh: null,
    summary: "The polished hatch. Fine for two adults. Not 4 stars.",
    caveat: "3-star GNCAP. Already no for a family shortlist.",
  },
  {
    id: "punch",
    year: 2025,
    make: "Tata",
    model: "Punch",
    trim: "Adventure",
    body: "compact-suv",
    condition: "new",
    auto: true,
    onRoad: 940000,
    seats: 5,
    kmpl: 18.8,
    fuel: "petrol",
    safety: 5,
    safetySource: "GNCAP",
    size: "small",
    parking: 8,
    reliability: 6,
    fun: 4,
    comfort: 6,
    trip: 6,
    cargo: 14,
    clearance: 8,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Micro-SUV that clears 5 stars without a Creta payment.",
    caveat: "Highway is noisy. Infotainment and fitment are not Hyundai.",
  },
  {
    id: "nexon",
    year: 2025,
    make: "Tata",
    model: "Nexon",
    trim: "Creative",
    body: "compact-suv",
    condition: "new",
    auto: true,
    onRoad: 1280000,
    seats: 5,
    kmpl: 17.4,
    fuel: "petrol",
    safety: 5,
    safetySource: "GNCAP",
    size: "medium",
    parking: 7,
    reliability: 6,
    fun: 5,
    comfort: 7,
    trip: 7,
    cargo: 18,
    clearance: 8,
    rangeKm: null,
    kmPerKwh: null,
    summary: "The default 5-star compact SUV if you can live with Tata service.",
    caveat: "Reliability is improved, not Maruti. Automatic dual-clutch has a history.",
  },
  {
    id: "venue",
    year: 2025,
    make: "Hyundai",
    model: "Venue",
    trim: "SX",
    body: "compact-suv",
    condition: "new",
    auto: true,
    onRoad: 1300000,
    seats: 5,
    kmpl: 18.0,
    fuel: "petrol",
    safety: 3,
    safetySource: "GNCAP",
    size: "medium",
    parking: 7,
    reliability: 7,
    fun: 5,
    comfort: 7,
    trip: 6,
    cargo: 16,
    clearance: 7,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Hyundai’s small SUV: features, dealer, and a 3-star crash test.",
    caveat: "Already no when kids are in the interview.",
  },
  {
    id: "brezza",
    year: 2025,
    make: "Maruti Suzuki",
    model: "Brezza",
    trim: "ZXi",
    body: "compact-suv",
    condition: "new",
    auto: true,
    onRoad: 1380000,
    seats: 5,
    kmpl: 19.8,
    fuel: "petrol",
    safety: 4,
    safetySource: "BNCAP",
    size: "medium",
    parking: 7,
    reliability: 9,
    fun: 4,
    comfort: 7,
    trip: 7,
    cargo: 18,
    clearance: 7,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Maruti service plus a 4-star compact SUV. The boring correct answer.",
    caveat: "Not the most cabin. Not the most fun. Usually the fewest workshop stories.",
  },
  {
    id: "xuv-3xo",
    year: 2025,
    make: "Mahindra",
    model: "XUV 3XO",
    trim: "MX3",
    body: "compact-suv",
    condition: "new",
    auto: true,
    onRoad: 1350000,
    seats: 5,
    kmpl: 18.2,
    fuel: "petrol",
    safety: 5,
    safetySource: "BNCAP",
    size: "medium",
    parking: 7,
    reliability: 6,
    fun: 6,
    comfort: 7,
    trip: 7,
    cargo: 17,
    clearance: 8,
    rangeKm: null,
    kmPerKwh: null,
    summary: "5-star compact SUV with more road presence than a Punch.",
    caveat: "Mahindra dealer quality varies by city. Check the workshop before you fall in love.",
  },
  {
    id: "grand-vitara-hybrid",
    year: 2025,
    make: "Maruti Suzuki",
    model: "Grand Vitara",
    trim: "Zeta Hybrid",
    body: "mid-suv",
    condition: "new",
    auto: true,
    onRoad: 1850000,
    seats: 5,
    kmpl: 27.5,
    fuel: "hybrid",
    safety: 0,
    safetySource: "unrated",
    size: "medium",
    parking: 6,
    reliability: 9,
    fun: 4,
    comfort: 8,
    trip: 8,
    cargo: 20,
    clearance: 7,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Strong hybrid that destroys city fuel bills — with no published 4-star rating in this catalog.",
    caveat: "Unrated here means already no for kids. Popular ≠ crash-tested.",
  },
  {
    id: "hyryder-hybrid",
    year: 2025,
    make: "Toyota",
    model: "Hyryder",
    trim: "S Hybrid",
    body: "mid-suv",
    condition: "new",
    auto: true,
    onRoad: 1900000,
    seats: 5,
    kmpl: 27.4,
    fuel: "hybrid",
    safety: 0,
    safetySource: "unrated",
    size: "medium",
    parking: 6,
    reliability: 9,
    fun: 4,
    comfort: 8,
    trip: 8,
    cargo: 20,
    clearance: 7,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Toyota hybrid twin of the Grand Vitara. Same efficiency, same missing Indian crash plaque.",
    caveat: "Already no for a family shortlist until there is a 4-star result on file.",
  },
  {
    id: "creta",
    year: 2025,
    make: "Hyundai",
    model: "Creta",
    trim: "SX petrol",
    body: "mid-suv",
    condition: "new",
    auto: true,
    onRoad: 1880000,
    seats: 5,
    kmpl: 17.2,
    fuel: "petrol",
    safety: 5,
    safetySource: "BNCAP",
    size: "medium",
    parking: 5,
    reliability: 7,
    fun: 5,
    comfort: 8,
    trip: 8,
    cargo: 22,
    clearance: 7,
    rangeKm: null,
    kmPerKwh: null,
    summary: "India’s default ‘yes’. This model can still mark it already no on monthly cap or parking.",
    caveat: "All-in is Creta money, not brochure EMI. Tight society stacks will hate it.",
  },
  {
    id: "seltos",
    year: 2025,
    make: "Kia",
    model: "Seltos",
    trim: "HTK+",
    body: "mid-suv",
    condition: "new",
    auto: true,
    onRoad: 1820000,
    seats: 5,
    kmpl: 17.0,
    fuel: "petrol",
    safety: 3,
    safetySource: "GNCAP",
    size: "medium",
    parking: 5,
    reliability: 7,
    fun: 6,
    comfort: 8,
    trip: 8,
    cargo: 22,
    clearance: 7,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Creta rival with a sharper cabin and a 3-star GNCAP score.",
    caveat: "Already no for kids. Looks are not a crash test.",
  },
  {
    id: "city",
    year: 2025,
    make: "Honda",
    model: "City",
    trim: "V",
    body: "sedan",
    condition: "new",
    auto: true,
    onRoad: 1650000,
    seats: 5,
    kmpl: 18.4,
    fuel: "petrol",
    safety: 5,
    safetySource: "ASEAN NCAP",
    size: "medium",
    parking: 6,
    reliability: 8,
    fun: 5,
    comfort: 8,
    trip: 8,
    cargo: 16,
    clearance: 4,
    rangeKm: null,
    kmPerKwh: null,
    summary: "The sedan that refused to die. Rear seat and Honda engines still matter on the highway.",
    caveat: "Low. Speed breakers and kuccha roads are a daily argument.",
  },
  {
    id: "virtus",
    year: 2025,
    make: "Volkswagen",
    model: "Virtus",
    trim: "Topline",
    body: "sedan",
    condition: "new",
    auto: true,
    onRoad: 1780000,
    seats: 5,
    kmpl: 18.1,
    fuel: "petrol",
    safety: 5,
    safetySource: "GNCAP",
    size: "medium",
    parking: 6,
    reliability: 6,
    fun: 8,
    comfort: 8,
    trip: 8,
    cargo: 17,
    clearance: 4,
    rangeKm: null,
    kmPerKwh: null,
    summary: "The 5-star sedan you buy if you still like driving and the highway.",
    caveat: "VW/Skoda service density is not Maruti. Ground clearance is a sedan.",
  },
  {
    id: "elevate",
    year: 2025,
    make: "Honda",
    model: "Elevate",
    trim: "VX",
    body: "mid-suv",
    condition: "new",
    auto: true,
    onRoad: 1680000,
    seats: 5,
    kmpl: 16.9,
    fuel: "petrol",
    safety: 5,
    safetySource: "ASEAN NCAP",
    size: "medium",
    parking: 6,
    reliability: 8,
    fun: 5,
    comfort: 8,
    trip: 8,
    cargo: 21,
    clearance: 7,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Honda’s Creta-fighter: space, 5 stars, fewer fireworks on the feature list.",
    caveat: "No diesel, no hybrid in this catalog row. All-in is still mid-SUV money.",
  },
  {
    id: "xuv700",
    year: 2025,
    make: "Mahindra",
    model: "XUV700",
    trim: "MX 7-seat",
    body: "mpv-suv",
    condition: "new",
    auto: true,
    onRoad: 2250000,
    seats: 7,
    kmpl: 15.0,
    fuel: "diesel",
    safety: 5,
    safetySource: "GNCAP",
    size: "large",
    parking: 3,
    reliability: 6,
    fun: 7,
    comfort: 8,
    trip: 9,
    cargo: 28,
    clearance: 8,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Seven seats, 5 stars, and a highway gait. A lot of car in a society lift.",
    caveat: "Already no on a tight monthly cap or a Mumbai street slot.",
  },
  {
    id: "harrier",
    year: 2025,
    make: "Tata",
    model: "Harrier",
    trim: "Adventure",
    body: "mid-suv",
    condition: "new",
    auto: true,
    onRoad: 2200000,
    seats: 5,
    kmpl: 14.6,
    fuel: "diesel",
    safety: 5,
    safetySource: "GNCAP",
    size: "large",
    parking: 4,
    reliability: 6,
    fun: 6,
    comfort: 8,
    trip: 9,
    cargo: 25,
    clearance: 8,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Five-seat diesel SUV for outstation kilometres, not for a lean EMI.",
    caveat: "Thirsty in traffic. Needs the highway week to make sense.",
  },
  {
    id: "safari",
    year: 2025,
    make: "Tata",
    model: "Safari",
    trim: "Adventure 7-seat",
    body: "mpv-suv",
    condition: "new",
    auto: true,
    onRoad: 2450000,
    seats: 7,
    kmpl: 14.5,
    fuel: "diesel",
    safety: 5,
    safetySource: "GNCAP",
    size: "large",
    parking: 3,
    reliability: 6,
    fun: 5,
    comfort: 8,
    trip: 9,
    cargo: 30,
    clearance: 8,
    rangeKm: null,
    kmPerKwh: null,
    summary: "The family diesel that actually has 5 stars and a third row.",
    caveat: "All-in monthly will scare a comfortable budget. Measure the basement.",
  },
  {
    id: "scorpio-n",
    year: 2025,
    make: "Mahindra",
    model: "Scorpio-N",
    trim: "Z4 7-seat",
    body: "mpv-suv",
    condition: "new",
    auto: true,
    onRoad: 2180000,
    seats: 7,
    kmpl: 14.0,
    fuel: "diesel",
    safety: 5,
    safetySource: "GNCAP",
    size: "large",
    parking: 3,
    reliability: 6,
    fun: 6,
    comfort: 7,
    trip: 9,
    cargo: 26,
    clearance: 9,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Bad-road family bus with a 5-star plaque. India still buys this shape for a reason.",
    caveat: "City parking is miserable. Fuel is diesel-highway logic.",
  },
  {
    id: "innova-hycross",
    year: 2025,
    make: "Toyota",
    model: "Innova Hycross",
    trim: "GX Hybrid",
    body: "mpv",
    condition: "new",
    auto: true,
    onRoad: 2850000,
    seats: 7,
    kmpl: 21.1,
    fuel: "hybrid",
    safety: 5,
    safetySource: "ASEAN NCAP",
    size: "large",
    parking: 3,
    reliability: 9,
    fun: 3,
    comfort: 9,
    trip: 10,
    cargo: 32,
    clearance: 6,
    rangeKm: null,
    kmPerKwh: null,
    summary: "The correct machine if people are the job and the monthly cap can take it.",
    caveat: "Already no under a stretch-or-less cap. You are buying a van. Own that.",
  },
  {
    id: "ertiga-cng",
    year: 2025,
    make: "Maruti Suzuki",
    model: "Ertiga",
    trim: "ZXi CNG",
    body: "mpv",
    condition: "new",
    auto: true,
    onRoad: 1420000,
    seats: 7,
    kmpl: 26.0,
    fuel: "cng",
    safety: 3,
    safetySource: "GNCAP",
    size: "medium",
    parking: 5,
    reliability: 9,
    fun: 3,
    comfort: 7,
    trip: 8,
    cargo: 24,
    clearance: 6,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Seven seats and factory CNG. The running-cost MPV for CNG metros.",
    caveat: "3-star. Already no for kids. CNG cities only.",
  },
  {
    id: "carens",
    year: 2025,
    make: "Kia",
    model: "Carens",
    trim: "Prestige",
    body: "mpv",
    condition: "new",
    auto: true,
    onRoad: 1600000,
    seats: 7,
    kmpl: 16.2,
    fuel: "petrol",
    safety: 3,
    safetySource: "GNCAP",
    size: "medium",
    parking: 5,
    reliability: 7,
    fun: 4,
    comfort: 8,
    trip: 8,
    cargo: 25,
    clearance: 6,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Sliding-door energy without calling it a van. 3-star GNCAP.",
    caveat: "Already no for a family shortlist that requires 4 stars.",
  },
  {
    id: "nexon-ev",
    year: 2025,
    make: "Tata",
    model: "Nexon EV",
    trim: "Creative+",
    body: "compact-suv",
    condition: "new",
    auto: true,
    onRoad: 1680000,
    seats: 5,
    kmpl: null,
    fuel: "ev",
    safety: 5,
    safetySource: "GNCAP",
    size: "medium",
    parking: 7,
    reliability: 6,
    fun: 6,
    comfort: 7,
    trip: 6,
    cargo: 17,
    clearance: 8,
    rangeKm: 325,
    kmPerKwh: 6.4,
    summary: "The volume Indian EV — only if a charger exists at home, not in the mall.",
    caveat: "No charger in the interview = already no. Outstation is a plan.",
  },
  {
    id: "punch-ev",
    year: 2025,
    make: "Tata",
    model: "Punch EV",
    trim: "Empowered",
    body: "compact-suv",
    condition: "new",
    auto: true,
    onRoad: 1390000,
    seats: 5,
    kmpl: null,
    fuel: "ev",
    safety: 5,
    safetySource: "GNCAP",
    size: "small",
    parking: 8,
    reliability: 6,
    fun: 4,
    comfort: 6,
    trip: 5,
    cargo: 14,
    clearance: 8,
    rangeKm: 275,
    kmPerKwh: 6.8,
    summary: "Cheaper EV all-in if you actually plug in at the society.",
    caveat: "Range is city-first. No home charger = already no.",
  },
  {
    id: "creta-electric",
    year: 2025,
    make: "Hyundai",
    model: "Creta Electric",
    trim: "Excellence",
    body: "mid-suv",
    condition: "new",
    auto: true,
    onRoad: 2280000,
    seats: 5,
    kmpl: null,
    fuel: "ev",
    safety: 5,
    safetySource: "BNCAP",
    size: "medium",
    parking: 5,
    reliability: 7,
    fun: 5,
    comfort: 8,
    trip: 7,
    cargo: 21,
    clearance: 7,
    rangeKm: 390,
    kmPerKwh: 6.2,
    summary: "Creta shape, electric bill — still Creta parking and Creta money.",
    caveat: "Needs a home charger. All-in can beat petrol Creta if kilometres are high.",
  },
  {
    id: "cpo-swift",
    year: 2021,
    make: "Maruti Suzuki",
    model: "Swift",
    trim: "True Value / CPO",
    body: "hatch",
    condition: "cpo",
    auto: false,
    onRoad: 540000,
    seats: 5,
    kmpl: 21.0,
    fuel: "petrol",
    safety: 2,
    safetySource: "older",
    size: "small",
    parking: 9,
    reliability: 8,
    fun: 6,
    comfort: 5,
    trip: 5,
    cargo: 9,
    clearance: 5,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Certified used, lower EMI. Only in play when the monthly cap is tight.",
    caveat: "Used/CPO is off unless you picked a tight all-in cap. Still 2-star.",
  },
  {
    id: "cpo-nexon",
    year: 2021,
    make: "Tata",
    model: "Nexon",
    trim: "CPO",
    body: "compact-suv",
    condition: "cpo",
    auto: true,
    onRoad: 880000,
    seats: 5,
    kmpl: 16.5,
    fuel: "petrol",
    safety: 5,
    safetySource: "GNCAP",
    size: "medium",
    parking: 7,
    reliability: 5,
    fun: 5,
    comfort: 6,
    trip: 6,
    cargo: 18,
    clearance: 8,
    rangeKm: null,
    kmPerKwh: null,
    summary: "Used 5-star compact SUV when a new Nexon blows the monthly cap.",
    caveat: "CPO only if the cap is tight. Get an independent inspection anyway.",
  },
];

export const BODY_LABELS = {
  hatch: "Hatchback",
  "compact-suv": "Compact SUV",
  "mid-suv": "Mid SUV",
  sedan: "Sedan",
  mpv: "MPV",
  "mpv-suv": "3-row SUV",
};

export function formatMoney(n) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(Math.round(n));
}

export function formatLakh(n) {
  const lakh = n / 100000;
  return `₹${lakh.toFixed(lakh >= 10 ? 1 : 2)} lakh`;
}

export function getCar(id) {
  return CARS.find((c) => c.id === id);
}
